name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

pool:
  name: Azure Pipelines
  vmImage: vs2017-win2016
  demands: java

steps:
  # TODO: Remove when Android Gradle Plugin 4.1 is stable.
  # Starting from AGP 4.1+, the required NDK version will be retrieved automatically, so this script will not be needed.
# - script: |
#    setx ANDROID_NDK_HOME ""
#    "%ANDROID_HOME%\tools\bin\sdkmanager.bat" --verbose "ndk;21.0.6113669"
#   displayName: 'Get NDK (TODO: Remove this step)'

- task: Gradle@2
  displayName: build
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:build'
    publishJUnitResults: false

- task: Gradle@2
  displayName: 'publish'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publish'
    publishJUnitResults: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
     **/io/adaptivecards/**/*.aar
     **/io/adaptivecards/**/*.pom
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true
  continueOnError: true
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
